name: Xamarin

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:

    Build:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
        
      - name: Restore NuGet 
        run: |
          nuget restore **/**.sln
          
      - name: Build Android App
        run: |                    
          msbuild ./Src/InvestmentDataSampleApp.Droid/InvestmentDataSampleApp.Droid.csproj /verbosity:normal /p:Configuration=Release

      - name: Build UI Test
        run: |                    
          msbuild ./Src/InvestmentDataSampleApp.UITests/InvestmentDataSampleApp.UITests.csproj /verbosity:normal /p:Configuration=Release
